name: CI/CD 배포 자동화 # 워크플로우의 이름을 붙이는 것

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 파일 불러오기
        uses: actions/checkout@v4

      - name: 빌드, 테스트를 위한 java17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: rds, s3 관련 파일 생성
        run: |
          echo "${{ secrets.db_config }}" > ./db_config.py

      - name: 빌드 및 테스트
        run: ./gradlew clean build

      - name: SCP 로 EC2 에 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: |
            ./db_config.py
          target: /home/ubuntu/AI-Server/config

      - name: 서버 배포
        uses: appleboy/ssh-action@v1.0.3 # 사용할 라이브러리 명시

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |
            git pull origin master
            cd ~/AI-Server
            source venv/bin/activate
            cd ~/deploy
            bash stop.sh
            bash start.sh
            bash health.sh
