name: CI/CD 배포 자동화 # 워크플로우의 이름을 붙이는 것

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:

      - name: rds, s3 관련 파일 생성
        run: |
          echo "${{ secrets.DB_CONFIG }}" > ./db_config.py

      - name: SCP 로 EC2 에 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: |
            ./db_config.py
          target: /home/ubuntu/AI-Server/config

      - name: 서버 배포
        uses: appleboy/ssh-action@v1.0.3 # 사용할 라이브러리 명시

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |
            git pull origin main
            cd ~/AI-Server
            source venv/bin/activate
            cd ~/deploy
            bash stop.sh
            bash start.sh
            bash health.sh
